###############################################################
#
#  This configures the robot to work with moveit studio
#
###############################################################

hardware:
  type: "kortex2_gen3"
  ip: "0.0.0.0"
  gripper_gear_ratio: 125.0 # Used to convert joint angles to desired position
  simulated: ${MOCK_HARDWARE:-true}
  launch_cameras_when_simulated: False

  robot_driver_persist_launch_file:
    package: "picknik_kinova_gen3_base_config"
    path: "launch/robot_drivers_to_persist.launch.py"

  simulated_robot_driver_persist_launch_file:
    package: "picknik_kinova_gen3_base_config"
    path: "launch/sim/robot_drivers_to_persist_sim.launch.py"

  camera_config_file:
    package: "picknik_kinova_gen3_base_config"
    path: "config/cameras.yaml"

  # These Params are pasted to the XACRO to create the URDF
  robot_description:
    urdf:
      package: "picknik_kinova_gen3_base_config"
      path: "description/picknik_kinova_gen3.xacro"
    srdf:
      package: "picknik_kinova_gen3_base_config"
      path: "config/moveit/picknik_kinova_gen3_base.srdf"
    urdf_params:
      - arm: "gen3"
      - dof: "7"
      - vision: "false"
      - robot_ip: "%>> hardware.ip"
      - gripper: "robotiq_2f_85"
      - username: "admin"
      - password: "admin"
      - port: "10000"
      - port_realtime: "10001"
      - session_inactivity_timeout_ms: "60000"
      - connection_inactivity_timeout_ms: "2000"
      - use_fake_hardware: "%>> hardware.simulated"
      - fake_sensor_commands: "false"
      - external_camera: "true"
      - wrist_realsense: "true"
      - sim_ignition: "false"
      - use_internal_bus_gripper_comm: "true"

optional_feature_params:
  use_joystick: False
  use_external_webcam: False
  use_formant_bridge: False

# This Configures moveit params that are in moveit_config.py
moveit_params:
  joint_group_name: "manipulator"

  ompl_planning:
    package: "picknik_kinova_gen3_base_config"
    path: "config/moveit/ompl_planning.yaml"
  kinematics:
    package: "picknik_kinova_gen3_base_config"
    path: "config/moveit/kinematics.yaml"
  servo:
    package: "picknik_kinova_gen3_base_config"
    path: "config/moveit/kinova_gen3_servo.yaml"
  sensors_3d:
    package: "picknik_kinova_gen3_base_config"
    path: "config/moveit/sensors_3d.yaml"
  joint_limits:
    package: "picknik_kinova_gen3_base_config"
    path: "config/moveit/joint_limits.yaml"

  publish:
    planning_scene: True
    geometry_updates: True
    state_updates: True
    transforms_updates: True

  trajectory_execution:
    manage_controllers: True
    allowed_execution_duration_scaling: 2.0
    allowed_goal_duration_margin: 5.0
    allowed_start_tolerance: 0.01

ui_params:
  servo_endpoint_frame_id: "tool_frame"

# This configures what controllers gets run at startup
ros2_control:
  config:
    package: "picknik_kinova_gen3_base_config"
    path: "config/control/picknik_kinova_gen3.ros2_control.yaml"
  # Load and start these controllers so they can be used immediately.
  controllers_active_at_startup:
    - "robotiq_gripper_controller"
    - "joint_state_broadcaster"
    - "joint_trajectory_controller"
    - "fault_controller"
  # TODO: Need the ability to enable empty list of inactive controllers at startup
  # Load but do not start these controllers so they can be activated later if needed.
  controllers_inactive_at_startup:
    - "streaming_controller" # this controller is currently not able to run at the same time as joint_trajectory_controller and is currently disabled in picknik_kinova_gen3.ros2_control.yaml

# Octomap manager configuration parameters
octomap_manager:
  # Input point cloud topic name. The *output* point cloud topic published by
  # the Octomap manager node is defined in sensors_3d.yaml.
  input_point_cloud_topic: "/wrist_mounted_camera/depth/color/points"

objectives:
  behavior_loader_plugins:
    core:
      - "moveit_studio::behaviors::CoreBehaviorsLoader"
  objective_library_paths:
    core:
      package_name: "picknik_kinova_gen3_base_config"
      relative_path: "objectives"
  waypoints_file:
    package_name: "picknik_kinova_gen3_base_config"
    relative_path: "waypoints/waypoints.yaml"
