- scene_camera:
    camera_name: "scene_camera"
    type: "realsense"
    use: True
    serial_no: "135322066258"
    device_type: "D415"
    framerate: 6
    image_width: 640
    image_height: 480
    enable_pointcloud: True

    # information about the topics the camera publishes the raw image and info
    rgb_info: "/scene_camera/color/camera_info"
    rgb_image: "/scene_camera/color/image_raw"

    json_file_path:
      package: "picknik_kinova_gen3_config"
      path: "config/realsense_config_high_accuracy.json"

    # By adding registered_rgb_depth_pair, This camera can be used for "Set Transform From Click"
    registered_rgb_depth_pair:
      depth_info: "/scene_camera/depth/camera_info"
      depth_image: "/scene_camera/depth/image_rect_raw"
      registered_info: "/scene_camera/depth_registered/camera_info"
      registered_image: "/scene_camera/depth_registered/image_rect"
