controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_trajectory_admittance_controller:
      type: joint_trajectory_admittance_controller/JointTrajectoryAdmittanceController

    twist_controller:
      type: picknik_twist_controller/PicknikTwistController

    # The gripper controller just relays position commands
    robotiq_gripper_controller:
      type: position_controllers/GripperActionController

    fault_controller:
      type: picknik_reset_fault_controller/PicknikResetFaultController

    servo_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    force_torque_sensor_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    joint_trajectory_admittance_controller:
      type: joint_trajectory_admittance_controller/JointTrajectoryAdmittanceController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - joint_7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.0
      goal_time: 10.0
      joint_1:
        goal: 0.05
      joint_2:
        goal: 0.05
      joint_3:
        goal: 0.05
      joint_4:
        goal: 0.05
      joint_5:
        goal: 0.05
      joint_6:
        goal: 0.05
      joint_7:
        goal: 0.05

joint_trajectory_admittance_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - joint_7
    base_frame: base_link
    sensor_frame: robotiq_ft_sensor
    ee_frame: grasp_link
    ft_sensor_name: robotiq_ft_sensor
    stop_accelerations: [3.0, 3.0, 3.0, 3.0, 5.0, 5.0, 5.0]

twist_controller:
  ros__parameters:
    joint: tcp
    interface_names:
      - twist.linear.x
      - twist.linear.y
      - twist.linear.z
      - twist.angular.x
      - twist.angular.y
      - twist.angular.z

robotiq_gripper_controller:
  ros__parameters:
    default: true
    joint: robotiq_85_left_knuckle_joint
    allow_stalling: true

servo_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - joint_7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    command_joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - joint_7
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.0
      goal_time: 0.0
      joint_1:
        goal: 0.05
      joint_2:
        goal: 0.05
      joint_3:
        goal: 0.05
      joint_4:
        goal: 0.05
      joint_5:
        goal: 0.05
      joint_6:
        goal: 0.05
      joint_7:
        goal: 0.05

force_torque_sensor_broadcaster:
  ros__parameters:
    sensor_name: robotiq_ft_sensor
    state_interface_names:
      - force.x
      - force.y
      - force.z
      - torque.x
      - torque.y
      - torque.z
    frame_id: fts_link


joint_trajectory_admittance_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - joint_7
    base_frame: base_link
    sensor_frame: fts_link
    ee_frame: grasp_link
    ft_sensor_name: robotiq_ft_sensor
    stop_accelerations: [3.0, 3.0, 3.0, 3.0, 5.0, 5.0, 5.0]
