FindSingularCuboids:
  base_frame: "world"

  # Distance threshold used when fitting a plane to the supporting surface.
  #   Increasing this value lets us fit to an uneven or noisy surface at the cost of preventing segmentation of short objects.
  #   Reducing this value allows detecting small objects on a very flat surface, but this will produce bad results for uneven or noisy surfaces.
  plane_model_threshold: 0.02

  # Distance threshold used when identifying clusters of points corresponding to distinct objects.
  #   Increasing this value makes the algorithm combine nearby discontinuous points into the same object, which lets the algorithm tolerate noisy data without introducing false positives at the cost of reduced accuracy.
  #   Reducing this value allows recognizing objects that are close to each other as distinct objects, but could increase the false positive rate.
  cluster_distance_threshold: 0.01

  # These define a rectangular region of interest relative to base_frame.
  #   The settings here define a 2m x 2m x 1m box just below the XY plane of the world frame.
  # Origin of the region:
  crop_box_origin_x: -1.0
  crop_box_origin_y: -1.0
  crop_box_origin_z: -0.03
  # Extent of the region:
  crop_box_size_x: 2.0
  crop_box_size_y: 2.0
  crop_box_size_z: 0.2

SetupMTCPickCuboid:
  # The lift vector points to the direction of the positive z-axis of the frame marked as the world frame.
  world_frame_name: "world"
  arm_group_name: "manipulator"
  end_effector_group_name: "gripper"
  end_effector_name: "gripper"
  hand_frame_name: "manual_grasp_link"
  end_effector_closed_pose_name: "close"
  ui_grasp_link: "manual_grasp_link"

  approach_distance: 0.1
  lift_distance: 0.1

  # These settings configure the motion planning constraint that prevents the robot from occluding the camera's view of the object while grasping.
  # Set to true to enforce this constraint. Set to false to ignore it.
  enforce_visibility_constraint: false  # Currently we disable this constraint since it makes motion planning take too long
  camera_optical_frame_id: "scene_camera_color_optical_frame"
  camera_field_of_view_angle: 0.0  # This is set to zero to disable checking if the object is within the camera field of view, since this check isn't useful when the camera is stationary.
  sensor_z_offset: 0.1  # Distance from the camera optical frame to the tip of the visibility cone. Needs to be non-zero to prevent reporting collisions between the cone and the camera geometry.
  target_diameter: 0.1  # Sets the diameter of the base of the visibility cone, which is centered on the target object

  # Grasp candidate configs
  grasp_candidate_config:
    generate_x_axis_grasps: true
    generate_y_axis_grasps: true
    generate_z_axis_grasps: true

    # Number of samples to generate for each quadrant of the cuboid.
    samples_per_quadrant: 3

  # Grasp data configs
  grasp_data:
    # See https://ros-planning.github.io/moveit_tutorials/_images/finger_gripper_explanation.jpg for description of the following parameters
    # Note: these parameters are copied from Robotiq gripper without tweaking
    # min/max values of the grasp depth range in meter.
    # This should fit to the distance from finger tip to inner palm or the suction cup stroke
    grasp_min_depth: 0.01 # minimum amount fingers must overlap object
    grasp_max_depth: 0.035 # Maximum distance from tip of end effector inwards that an object can be for a grasp
    # Maximum allowed finger width for a grasp.
    # This value should be considerably smaller than max_finger_width
    # to allow padded collision checks
    max_grasp_width: 0.09
    
    # The transform from the arm IK link to the grasp point to align it with the following convention.
    #
    # z-axis pointing toward object to grasp
    # x-axis perpendicular to movement of grippers
    # y-axis parallel to movement of grippers
    eef_mount_to_tcp_transform:
      x: 0.0
      y: 0.0
      z: 0.0
      roll: 0.0
      pitch: 0.0
      yaw: 1.57
      
IsConstraintSatisfied:
  camera_optical_frame_id: "scene_camera_color_optical_frame"
  camera_field_of_view_angle: 0.0  
  sensor_z_offset: 0.1  
  target_diameter: 0.2
